const FilterTypes = {
    GET_RESULTS_START: 'GET_RESULTS_START',
    GET_RESULTS_SUCCESS: 'GET_RESULTS_SUCCESS',
    GET_RESULTS_FAILURE: 'GET_RESULTS_FAILURE',
    SET_FILTERS: 'SET_FILTERS',
    CLEAR_FILTERS: 'CLEAR_FILTERS'
}

export default FilterTypes;