const PerfumeTypes = {
    GET_ALL_PERFUMES_START: 'GET_ALL_PERFUMES_START',
    GET_ALL_PERFUMES_SUCCESS: 'GET_ALL_PERFUMES_SUCCESS',
    GET_ALL_PERFUMES_FAILURE: 'GET_ALL_PERFUMES_FAILURE',
    GET_SPECIAL_START: 'GET_SPECIAL_START',
    GET_SPECIAL_SUCCESS: 'GET_SPECIAL_SUCCESS',
    GET_SPECIAL_FAILURE: 'GET_SPECIAL_FAILURE',
    GET_PERFUME_DETAILS_START: 'GET_PERFUME_DETAILS_START',
    GET_PERFUME_DETAILS_SUCCESS: 'GET_PERFUME_DETAILS_SUCCESS',
    GET_PERFUME_DETAILS_FAILURE: 'GET_PERFUME_DETAILS_FAILURE'
};

export default PerfumeTypes