const CollectionTypes = {
    GET_COLLECTION_START: 'GET_COLLECTION_START',
    GET_COLLECTION_SUCCESS: 'GET_COLLECTION_SUCCESS',
    GET_COLLECTION_FAILURE: 'GET_COLLECTION_FAILURE',
};

export default CollectionTypes;